name: local_gan
channels:
  - defaults
  - pytorch
dependencies:
  - python=3.8
  - pytorch
  - torchvision
  - numpy
  - pandas
  - poetry
  - ipykernel
  - pip
  - pip:
    - sentencepiece
    - sacrebleu
    - tensorboard